### ISSUE TITLE
Not working on Nostalrius Begins, 1.12.1

### ISSUE THREAD

**Issue by v2px** [tjmnmk/tclib#2]
> unpack requires a string argument of length 4
> Traceback (most recent call last):
>   File "/home/wowbridge/.local/lib/python2.7/site-packages/tclib/realm/realm.py", line 71, in run
>     self._handlers[cmd]()
>   File "/home/wowbridge/.local/lib/python2.7/site-packages/tclib/realm/realm.py", line 360, in _handle_realm_list
>    realmtype = buff.get("I")
>   File "/home/wowbridge/.local/lib/python2.7/site-packages/tclib/shared/bytebuff.py", line 309, in get
>     unpacked = struct.unpack(order + fmt_item, self.data[self._position:fmt_item_end])
> error: unpack requires a string argument of length 4

Python 2.7.3
tclib @008cf3a453ce951a58d64071a51a0af36271e503
tested with tcbot

**Comment by tjmnmk** [comment]
fixed by commit @e21f38076c019f973d0149fa9e9c4b8485e7634c

Please update also tcbot ( https://github.com/meggie-true/tcbot/commit/1453812c205175da2204ac5fe7da6a1ba668654c https://github.com/meggie-true/tcbot/commit/0b7534454e12ed7d3ac446fb6e5926434a731c13) .

**Comment by v2px** [comment]
@meggie-true awesome, thank you!
@changetip $0.5
